### PR TITLE
Update billing.json

### PR DESCRIPTION
**Pull request by shahabhijeet**
Creating alpha api version

### CODE REVIEW

**Comment by adxsdknet** [comment]
startbuild

**Comment by adxsdknet** [comment]
startbuild

**Comment by adxsdknet** [comment]
startbuild

**Comment by adxsdknet** [comment]
startbuild

**Comment by adxsdknet** [comment]
startbuild

**Comment by adxsdknet** [comment]
startbuild

**Comment by adxsdknet** [comment]
startbuild

**Comment by adxsdknet** [comment]
startbuild

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net 
A PR has been created for you: 
https://github.com/azure/aznetsdk/pull/82 
.NET SDK Commits: 
https://github.com/adxsdknet/aznetsdk/pull/82/commits/2aea3884ba57fdb825aaab93a3b161aefae855ea

**Comment by shahabhijeet** [comment]
[Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg.zip](https://github.com/Azure/AzSwaggerSpecsTestClone/files/2990850/Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg.zip)

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net \nA nuget package has been generated for you: \n[Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg](\\scratch2\scratch\stos\RestSpecPr\AzSwaggerSpecsTestClone\108\Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg)

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net
A nuget package has been generated for you:
[Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg](\\scratch2\scratch\stos\RestSpecPr\AzSwaggerSpecsTestClone\108\Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg)

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net
A nuget package has been generated for you:
[Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg](\\scratch2\scratch\stos\RestSpecPr\AzSwaggerSpecsTestClone\108\Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg)
Total time spent: 0.62814912 mins.

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net
A nuget package has been generated for you:
[Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg](\\scratch2\scratch\stos\RestSpecPr\AzSwaggerSpecsTestClone\108\Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg)
Total time spent: 1.372869955 mins.

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net
A nuget package has been generated for you:
[Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg](\\scratch2\scratch\stos\RestSpecPr\AzSwaggerSpecsTestClone\108\Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg)
Total time spent: 0.787439923333333 mins.

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net
A nuget package has been generated for you:
[Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg](\\scratch2\scratch\stos\RestSpecPr\AzSwaggerSpecsTestClone\108\Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg)
Total time spent: 0.60741515 mins.

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net
A nuget package has been generated for you:
[Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg](\\scratch2\scratch\stos\RestSpecPr\AzSwaggerSpecsTestClone\108\Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg)
Total time spent: 1.35249788666667 mins.

**Pull request closed without merging**
