### PR TITLE
Adding changes for billing new API

### PR DESCRIPTION
**Pull request by shahabhijeet**
Creating alpha api version

### CODE REVIEW

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net
A nuget package has been generated for you:
[Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg](\\scratch2\scratch\stos\RestSpecPr\AzSwaggerSpecsTestClone\119\Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg)
Total time spent: 2.168204405 mins.

**Comment by shahabhijeet** [comment]
startbuild

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net
A nuget package has been generated for you:
[Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg](\\scratch2\scratch\stos\RestSpecPr\AzSwaggerSpecsTestClone\119\Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg)
Total time spent: 2.01926484833333 mins.

**Comment by shahabhijeet** [comment]
startbuild

**Comment by adxsdknet** [comment]
# Automation for azure-sdk-for-net
A nuget package has been generated for you:
[Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg](\\scratch2\scratch\stos\RestSpecPr\AzSwaggerSpecsTestClone\119\Microsoft.Azure.Management.Billing.2.1.1-preview.nupkg)
Total time spent: 2.08685815 mins.

**Pull request closed without merging**
